---
galaxy_info:
  author: Max
  role_name: prometheus2
  description: Prometheus monitoring system configuration and management
  company: none
  min_ansible_version: 2.7
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - stretch
        - buster
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 30
        - 31

dependencies: []
